labels: [question]
body:
  - type: checkboxes
    id: guidelines
    attributes:
      label: Contributing guidelines
      options:
      - label: I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
        required: true
  - type: dropdown
    id: module
    attributes:
      label: "Module(s)"
      description: "Choose one or several modules this question is related to"
      multiple: true
      options:
        - mini.ai
        - mini.align
        - mini.animate
        - mini.base16
        - mini.basics
        - mini.bracketed
        - mini.bufremove
        - mini.clue
        - mini.colors
        - mini.comment
        - mini.completion
        - mini.cursorword
        - mini.deps
        - mini.diff
        - mini.doc
        - mini.extra
        - mini.files
        - mini.fuzzy
        - mini.git
        - mini.hipatterns
        - mini.hues
        - mini.icons
        - mini.indentscope
        - mini.jump
        - mini.jump2d
        - mini.keymap
        - mini.map
        - mini.misc
        - mini.move
        - mini.notify
        - mini.operators
        - mini.pairs
        - mini.pick
        - mini.sessions
        - mini.snippets
        - mini.splitjoin
        - mini.starter
        - mini.statusline
        - mini.surround
        - mini.tabline
        - mini.test
        - mini.trailspace
        - mini.visits
        - none of the above
        - all of the above
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Question"
    validations:
      required: true

